// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDir(arg1) {
  return window['go']['main']['App']['ChangeDir'](arg1);
}

export function ChangeRepeatMode() {
  return window['go']['main']['App']['ChangeRepeatMode']();
}

export function ChangeSong(arg1) {
  return window['go']['main']['App']['ChangeSong'](arg1);
}

export function GetCurrentSongData() {
  return window['go']['main']['App']['GetCurrentSongData']();
}

export function GetQueueData() {
  return window['go']['main']['App']['GetQueueData']();
}

export function Next() {
  return window['go']['main']['App']['Next']();
}

export function PollTimeMilliSeconds() {
  return window['go']['main']['App']['PollTimeMilliSeconds']();
}

export function Prev() {
  return window['go']['main']['App']['Prev']();
}

export function SeekTimeMilliseconds(arg1) {
  return window['go']['main']['App']['SeekTimeMilliseconds'](arg1);
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
