// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';

export function ChangeDir(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function NotifyEvent(arg1:audio.AudioEvent):Promise<void>;
