// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';

export function ChangeDir(arg1:string):Promise<void>;

export function ChangeRepeatMode():Promise<audio.RepeatOption>;

export function ChangeSong(arg1:number):Promise<void>;

export function GetCurrentSongData():Promise<audio.Metadata>;

export function Next():Promise<void>;

export function PollTimeMilliSeconds():Promise<number>;

export function Prev():Promise<void>;

export function SeekTimeMilliseconds(arg1:number):Promise<void>;

export function TogglePause():Promise<boolean>;
